<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210419114324 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA old_records');
        $this->addSql('CREATE TABLE auction_offers (id UUID NOT NULL, bid_id UUID DEFAULT NULL, auction_id UUID DEFAULT NULL, cost VARCHAR(255) NOT NULL, client_ip VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sign TEXT NOT NULL, hash VARCHAR(255) NOT NULL, xml TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A3D5A81A4D9866B8 ON auction_offers (bid_id)');
        $this->addSql('CREATE INDEX IDX_A3D5A81A57B8F0DE ON auction_offers (auction_id)');
        $this->addSql('COMMENT ON COLUMN auction_offers.cost IS \'(DC2Type:money)\'');
        $this->addSql('COMMENT ON COLUMN auction_offers.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE auctions (id UUID NOT NULL, winner_id UUID DEFAULT NULL, lot_id UUID DEFAULT NULL, status VARCHAR(255) NOT NULL, current_cost VARCHAR(255) NOT NULL, final_cost VARCHAR(255) DEFAULT NULL, default_closed_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, offer_auction_time VARCHAR(255) NOT NULL, auction_step VARCHAR(255) NOT NULL, start_trading_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_ip VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_72D6E9005DFCD4B8 ON auctions (winner_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_72D6E900A8CBA5F7 ON auctions (lot_id)');
        $this->addSql('COMMENT ON COLUMN auctions.winner_id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN auctions.current_cost IS \'(DC2Type:money)\'');
        $this->addSql('COMMENT ON COLUMN auctions.final_cost IS \'(DC2Type:money)\'');
        $this->addSql('COMMENT ON COLUMN auctions.default_closed_time IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN auctions.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN auctions.closed_time IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN auctions.auction_step IS \'(DC2Type:money)\'');
        $this->addSql('COMMENT ON COLUMN auctions.start_trading_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE bid_documents (id UUID NOT NULL, bid_id UUID NOT NULL, status VARCHAR(255) NOT NULL, document_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, participant_ip VARCHAR(255) NOT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, file_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_size INT NOT NULL, file_real_name VARCHAR(255) NOT NULL, file_sign TEXT DEFAULT NULL, file_hash VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_388B21574D9866B8 ON bid_documents (bid_id)');
        $this->addSql('COMMENT ON COLUMN bid_documents.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bid_documents.signed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE bid_xml_documents (id UUID NOT NULL, bid_id UUID DEFAULT NULL, status VARCHAR(255) NOT NULL, file TEXT NOT NULL, hash VARCHAR(255) NOT NULL, sign TEXT DEFAULT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_33B397D54D9866B8 ON bid_xml_documents (bid_id)');
        $this->addSql('COMMENT ON COLUMN bid_xml_documents.signed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bid_xml_documents.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE bids (id UUID NOT NULL, participant_id UUID NOT NULL, lot_id UUID DEFAULT NULL, requisite_id VARCHAR(255) DEFAULT NULL, subscribe_tariff_id VARCHAR(255) DEFAULT NULL, number INT NOT NULL, status VARCHAR(255) NOT NULL, place INT DEFAULT NULL, participant_ip VARCHAR(255) NOT NULL, organizer_ip VARCHAR(255) DEFAULT NULL, organizer_comment TEXT DEFAULT NULL, organizer_comment_sign TEXT DEFAULT NULL, organizer_ip_created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, confirm_xml TEXT DEFAULT NULL, confirm_sign TEXT DEFAULT NULL, confirm_hash VARCHAR(255) DEFAULT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3FF09E1E9D1C3019 ON bids (participant_id)');
        $this->addSql('CREATE INDEX IDX_3FF09E1EA8CBA5F7 ON bids (lot_id)');
        $this->addSql('CREATE INDEX IDX_3FF09E1E95EDF9EA ON bids (requisite_id)');
        $this->addSql('CREATE INDEX IDX_3FF09E1E7599DDED ON bids (subscribe_tariff_id)');
        $this->addSql('COMMENT ON COLUMN bids.participant_id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN bids.requisite_id IS \'(DC2Type:profile_requisite_id)\'');
        $this->addSql('COMMENT ON COLUMN bids.organizer_ip_created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bids.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bids.signed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE certificates (id UUID NOT NULL, user_id VARCHAR(255) NOT NULL, thumbprint VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, archived_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, sign TEXT DEFAULT \'sign\' NOT NULL, subject_name_ogrn VARCHAR(255) DEFAULT NULL, subject_name_ogrn_ip VARCHAR(255) DEFAULT NULL, subject_name_snils VARCHAR(255) NOT NULL, subject_name_inn VARCHAR(255) NOT NULL, subject_name_email VARCHAR(255) DEFAULT NULL, subject_name_owner VARCHAR(255) DEFAULT NULL, subject_name_position VARCHAR(255) DEFAULT NULL, subject_name_user_name VARCHAR(255) NOT NULL, subject_name_region VARCHAR(255) DEFAULT NULL, subject_name_city VARCHAR(255) DEFAULT NULL, subject_name_street VARCHAR(255) DEFAULT NULL, issuer_name_issuer VARCHAR(255) NOT NULL, issuer_name_unit_organization VARCHAR(255) DEFAULT NULL, issuer_name_inn VARCHAR(255) NOT NULL, issuer_name_ogrn VARCHAR(255) NOT NULL, issuer_name_email VARCHAR(255) DEFAULT NULL, issuer_name_region VARCHAR(255) NOT NULL, issuer_name_city VARCHAR(255) NOT NULL, issuer_name_street VARCHAR(255) NOT NULL, confirm_token_token VARCHAR(255) DEFAULT NULL, confirm_token_expires TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D26FB5F638AF9D3 ON certificates (thumbprint)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D26FB5FF464BC96 ON certificates (confirm_token_token)');
        $this->addSql('CREATE INDEX IDX_8D26FB5FA76ED395 ON certificates (user_id)');
        $this->addSql('COMMENT ON COLUMN certificates.id IS \'(DC2Type:certificate_id)\'');
        $this->addSql('COMMENT ON COLUMN certificates.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN certificates.archived_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN certificates.valid_from IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN certificates.valid_to IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN certificates.confirm_token_expires IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE commission_members (id UUID NOT NULL, commission_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_name VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, middle_name VARCHAR(255) NOT NULL, positions VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EC75342F202D1EB2 ON commission_members (commission_id)');
        $this->addSql('COMMENT ON COLUMN commission_members.id IS \'(DC2Type:member_id)\'');
        $this->addSql('COMMENT ON COLUMN commission_members.commission_id IS \'(DC2Type:commission_id)\'');
        $this->addSql('COMMENT ON COLUMN commission_members.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN commission_members.archived_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE commissions (id UUID NOT NULL, profile_id UUID NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7EA273CCCCFA12B8 ON commissions (profile_id)');
        $this->addSql('COMMENT ON COLUMN commissions.id IS \'(DC2Type:commission_id)\'');
        $this->addSql('COMMENT ON COLUMN commissions.profile_id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN commissions.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN commissions.archived_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN commissions.changed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE old_records.documents (id VARCHAR(255) NOT NULL, procedure_id UUID DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, path TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8B3415DB1624BCD2 ON old_records.documents (procedure_id)');
        $this->addSql('COMMENT ON COLUMN old_records.documents.id IS \'(DC2Type:old_document_id)\'');
        $this->addSql('COMMENT ON COLUMN old_records.documents.procedure_id IS \'(DC2Type:old_procedure_id)\'');
        $this->addSql('CREATE TABLE holidays (id UUID NOT NULL, date_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN holidays.date_start IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN holidays.date_end IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE levels (id VARCHAR(255) NOT NULL, id_tariff VARCHAR(255) NOT NULL, priority INT NOT NULL, amount VARCHAR(255) NOT NULL, percent DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9F2A6419B2529590 ON levels (id_tariff)');
        $this->addSql('COMMENT ON COLUMN levels.amount IS \'(DC2Type:money)\'');
        $this->addSql('COMMENT ON COLUMN levels.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE lot_documents (id UUID NOT NULL, lot_id UUID NOT NULL, status VARCHAR(255) NOT NULL, document_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, participant_ip VARCHAR(255) NOT NULL, file_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_size INT NOT NULL, file_real_name VARCHAR(255) NOT NULL, file_sign TEXT DEFAULT NULL, file_hash VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_83A64CCCA8CBA5F7 ON lot_documents (lot_id)');
        $this->addSql('COMMENT ON COLUMN lot_documents.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE lots (id UUID NOT NULL, procedure_id UUID DEFAULT NULL, auction_id UUID NOT NULL, id_number INT NOT NULL, arrested_property_type VARCHAR(255) NOT NULL, reload_lot VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, tender_basic TEXT NOT NULL, date_enforcement_proceedings VARCHAR(255) NOT NULL, nds VARCHAR(255) NOT NULL, start_date_of_applications TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closing_date_of_applications TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, summing_up_applications TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, debtor_full_name VARCHAR(255) NOT NULL, debtor_full_name_date_case VARCHAR(255) NOT NULL, deposit_policy TEXT NOT NULL, lot_name TEXT NOT NULL, region VARCHAR(255) NOT NULL, pledgeer VARCHAR(255) DEFAULT NULL, location_object VARCHAR(255) NOT NULL, additional_object_characteristics TEXT DEFAULT NULL, starting_price VARCHAR(255) NOT NULL, bailiffs_name TEXT NOT NULL, bailiffs_name_dative_case TEXT NOT NULL, executive_production_number TEXT NOT NULL, client_ip VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, requisite TEXT NOT NULL, advance_payment_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deposit_amount VARCHAR(255) NOT NULL, payment_winner_confirm TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_916087CE1624BCD2 ON lots (procedure_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_916087CE57B8F0DE ON lots (auction_id)');
        $this->addSql('COMMENT ON COLUMN lots.procedure_id IS \'(DC2Type:procedure_id)\'');
        $this->addSql('COMMENT ON COLUMN lots.start_date_of_applications IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN lots.closing_date_of_applications IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN lots.summing_up_applications IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN lots.starting_price IS \'(DC2Type:money)\'');
        $this->addSql('COMMENT ON COLUMN lots.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN lots.advance_payment_time IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN lots.deposit_amount IS \'(DC2Type:money)\'');
        $this->addSql('CREATE TABLE news (id UUID NOT NULL, status VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, text TEXT NOT NULL, delayed_publication TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN news.delayed_publication IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN news.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE old_records.notice (id UUID NOT NULL, procedure_id UUID NOT NULL, name TEXT NOT NULL, text TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_94AF0DF81624BCD2 ON old_records.notice (procedure_id)');
        $this->addSql('COMMENT ON COLUMN old_records.notice.id IS \'(DC2Type:old_notice_id)\'');
        $this->addSql('COMMENT ON COLUMN old_records.notice.procedure_id IS \'(DC2Type:old_procedure_id)\'');
        $this->addSql('CREATE TABLE notifications (id VARCHAR(255) NOT NULL, user_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, content_subject VARCHAR(255) NOT NULL, content_text TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('COMMENT ON COLUMN notifications.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifications.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE payment_transactions (id VARCHAR(255) NOT NULL, bid_id UUID DEFAULT NULL, payment_id VARCHAR(255) DEFAULT NULL, requisite_id VARCHAR(255) DEFAULT NULL, id_number VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, money VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, xml TEXT DEFAULT NULL, hash VARCHAR(255) DEFAULT NULL, sign TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8C58AD564D9866B8 ON payment_transactions (bid_id)');
        $this->addSql('CREATE INDEX IDX_8C58AD564C3A3BB ON payment_transactions (payment_id)');
        $this->addSql('CREATE INDEX IDX_8C58AD5695EDF9EA ON payment_transactions (requisite_id)');
        $this->addSql('COMMENT ON COLUMN payment_transactions.requisite_id IS \'(DC2Type:profile_requisite_id)\'');
        $this->addSql('COMMENT ON COLUMN payment_transactions.money IS \'(DC2Type:money)\'');
        $this->addSql('COMMENT ON COLUMN payment_transactions.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN payment_transactions.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE procedure_documents (id VARCHAR(255) NOT NULL, procedure_id UUID NOT NULL, status VARCHAR(255) NOT NULL, file_type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_ip VARCHAR(255) DEFAULT NULL, file_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_size INT NOT NULL, file_real_name VARCHAR(255) NOT NULL, file_sign TEXT DEFAULT NULL, file_hash VARCHAR(255) DEFAULT NULL, file_signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6DD360031624BCD2 ON procedure_documents (procedure_id)');
        $this->addSql('CREATE INDEX IDX_6DD360038B8E8428 ON procedure_documents (created_at)');
        $this->addSql('COMMENT ON COLUMN procedure_documents.id IS \'(DC2Type:procedure_document_id)\'');
        $this->addSql('COMMENT ON COLUMN procedure_documents.procedure_id IS \'(DC2Type:procedure_id)\'');
        $this->addSql('COMMENT ON COLUMN procedure_documents.file_type IS \'(DC2Type:procedure_document_type)\'');
        $this->addSql('COMMENT ON COLUMN procedure_documents.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN procedure_documents.file_signed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE procedure_xml_document_history (id UUID NOT NULL, xml_document_id UUID DEFAULT NULL, moderator_id VARCHAR(255) DEFAULT NULL, action VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_ip VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A851F434573F85BD ON procedure_xml_document_history (xml_document_id)');
        $this->addSql('CREATE INDEX IDX_A851F434D0AFA354 ON procedure_xml_document_history (moderator_id)');
        $this->addSql('COMMENT ON COLUMN procedure_xml_document_history.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE procedure_xml_documents (id UUID NOT NULL, procedure_id UUID DEFAULT NULL, moderator_id VARCHAR(255) DEFAULT NULL, number VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, status_tactic VARCHAR(255) NOT NULL, file TEXT NOT NULL, hash VARCHAR(255) NOT NULL, sign TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, moderator_comment VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6FE79AF01624BCD2 ON procedure_xml_documents (procedure_id)');
        $this->addSql('CREATE INDEX IDX_6FE79AF0D0AFA354 ON procedure_xml_documents (moderator_id)');
        $this->addSql('COMMENT ON COLUMN procedure_xml_documents.procedure_id IS \'(DC2Type:procedure_id)\'');
        $this->addSql('COMMENT ON COLUMN procedure_xml_documents.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN procedure_xml_documents.signed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE procedures (id UUID NOT NULL, profile_id UUID NOT NULL, organization_id VARCHAR(255) DEFAULT NULL, representative_id VARCHAR(255) DEFAULT NULL, id_number INT NOT NULL, price_presentation_form VARCHAR(255) NOT NULL, info_point_entry TEXT NOT NULL, info_trading_venue TEXT NOT NULL, info_bidding_process TEXT NOT NULL, tendering_process TEXT NOT NULL, title TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, contract_type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, organizer_full_name VARCHAR(255) NOT NULL, organizer_email VARCHAR(255) NOT NULL, organizer_phone VARCHAR(255) NOT NULL, client_ip VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_969AFE42CCFA12B8 ON procedures (profile_id)');
        $this->addSql('CREATE INDEX IDX_969AFE4232C8A3DE ON procedures (organization_id)');
        $this->addSql('CREATE INDEX IDX_969AFE42FC3FF006 ON procedures (representative_id)');
        $this->addSql('COMMENT ON COLUMN procedures.id IS \'(DC2Type:procedure_id)\'');
        $this->addSql('COMMENT ON COLUMN procedures.profile_id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN procedures.organization_id IS \'(DC2Type:profile_organization_id)\'');
        $this->addSql('COMMENT ON COLUMN procedures.representative_id IS \'(DC2Type:profile_representative_id)\'');
        $this->addSql('COMMENT ON COLUMN procedures.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE old_records.procedures (id UUID NOT NULL, id_number INT NOT NULL, tender_basic TEXT NOT NULL, price_presentation_form VARCHAR(255) NOT NULL, organizer VARCHAR(255) NOT NULL, start_date_of_applications VARCHAR(255) NOT NULL, closing_date_of_applications VARCHAR(255) NOT NULL, start_trading_date VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, reload_lot VARCHAR(255) NOT NULL, auction_step VARCHAR(255) NOT NULL, start_cost VARCHAR(255) NOT NULL, nds VARCHAR(255) NOT NULL, deposit_amount VARCHAR(255) NOT NULL, arrested_property_type VARCHAR(255) NOT NULL, additional_object_characteristics TEXT DEFAULT NULL, region VARCHAR(255) NOT NULL, location_object VARCHAR(255) NOT NULL, organizer_short_name VARCHAR(255) NOT NULL, organizer_full_name VARCHAR(255) NOT NULL, organizer_contact_full_name VARCHAR(255) NOT NULL, organizer_phone VARCHAR(255) NOT NULL, organizer_email VARCHAR(255) NOT NULL, organizer_legal_address VARCHAR(255) NOT NULL, debtor_full_name VARCHAR(255) NOT NULL, procedure_info_applications VARCHAR(255) NOT NULL, procedure_info_place VARCHAR(255) NOT NULL, procedure_info_location VARCHAR(255) NOT NULL, lot_name VARCHAR(255) NOT NULL, text_notification VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN old_records.procedures.id IS \'(DC2Type:old_procedure_id)\'');
        $this->addSql('CREATE TABLE profile_documents (id VARCHAR(255) NOT NULL, profile_id UUID NOT NULL, file_type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, client_ip VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, file_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_size INT NOT NULL, file_real_name VARCHAR(255) NOT NULL, file_sign TEXT DEFAULT NULL, file_sign_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, file_hash VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1E2F9BF3CCFA12B8 ON profile_documents (profile_id)');
        $this->addSql('CREATE INDEX IDX_1E2F9BF38B8E8428 ON profile_documents (created_at)');
        $this->addSql('COMMENT ON COLUMN profile_documents.id IS \'(DC2Type:profile_document_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_documents.profile_id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_documents.file_type IS \'(DC2Type:profile_document_type)\'');
        $this->addSql('COMMENT ON COLUMN profile_documents.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN profile_documents.file_sign_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE profile_organizations (id VARCHAR(255) NOT NULL, profile_id UUID NOT NULL, inn VARCHAR(12) NOT NULL, fact_country TEXT NOT NULL, fact_region TEXT NOT NULL, fact_city TEXT NOT NULL, fact_index TEXT NOT NULL, fact_street TEXT NOT NULL, fact_house TEXT NOT NULL, legal_country TEXT NOT NULL, legal_region TEXT NOT NULL, legal_city TEXT NOT NULL, legal_index TEXT NOT NULL, legal_street TEXT NOT NULL, legal_house TEXT NOT NULL, full_title_organization VARCHAR(255) DEFAULT NULL, short_title_organization VARCHAR(255) DEFAULT NULL, kpp VARCHAR(9) DEFAULT NULL, ogrn VARCHAR(15) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_ip VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6C7FB9BFCCFA12B8 ON profile_organizations (profile_id)');
        $this->addSql('COMMENT ON COLUMN profile_organizations.id IS \'(DC2Type:profile_organization_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_organizations.profile_id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_organizations.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN profile_organizations.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE profile_payments (id VARCHAR(255) NOT NULL, profile_id UUID DEFAULT NULL, invoice_number VARCHAR(255) NOT NULL, available_amount VARCHAR(255) NOT NULL, blocked_amount VARCHAR(255) NOT NULL, withdrawal_amount VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9CB8FA832DA68207 ON profile_payments (invoice_number)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9CB8FA83CCFA12B8 ON profile_payments (profile_id)');
        $this->addSql('COMMENT ON COLUMN profile_payments.profile_id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_payments.available_amount IS \'(DC2Type:money)\'');
        $this->addSql('COMMENT ON COLUMN profile_payments.blocked_amount IS \'(DC2Type:money)\'');
        $this->addSql('COMMENT ON COLUMN profile_payments.withdrawal_amount IS \'(DC2Type:money)\'');
        $this->addSql('COMMENT ON COLUMN profile_payments.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE profile_profiles (id UUID NOT NULL, role_id UUID NOT NULL, user_id VARCHAR(255) NOT NULL, organization_id VARCHAR(255) DEFAULT NULL, representative_id VARCHAR(255) DEFAULT NULL, certificate_id UUID NOT NULL, subscribe_tariff_id VARCHAR(255) DEFAULT NULL, payment_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, incorporated_form VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, client_ip VARCHAR(255) NOT NULL, contract_period TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, web_site VARCHAR(255) DEFAULT NULL, registration_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_725AE481D60322AC ON profile_profiles (role_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_725AE481A76ED395 ON profile_profiles (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_725AE48132C8A3DE ON profile_profiles (organization_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_725AE481FC3FF006 ON profile_profiles (representative_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_725AE48199223FFD ON profile_profiles (certificate_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_725AE4817599DDED ON profile_profiles (subscribe_tariff_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_725AE4814C3A3BB ON profile_profiles (payment_id)');
        $this->addSql('COMMENT ON COLUMN profile_profiles.id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_profiles.role_id IS \'(DC2Type:role_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_profiles.organization_id IS \'(DC2Type:profile_organization_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_profiles.representative_id IS \'(DC2Type:profile_representative_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_profiles.certificate_id IS \'(DC2Type:certificate_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_profiles.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN profile_profiles.contract_period IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN profile_profiles.registration_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE profile_representatives (id VARCHAR(255) NOT NULL, profile_id UUID NOT NULL, position VARCHAR(255) DEFAULT NULL, confirming_document VARCHAR(255) DEFAULT NULL, phone VARCHAR(11) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_ip VARCHAR(255) DEFAULT NULL, passport_first_name VARCHAR(255) NOT NULL, passport_middle_name VARCHAR(255) NOT NULL, passport_last_name VARCHAR(255) NOT NULL, passport_series VARCHAR(4) DEFAULT NULL, passport_number VARCHAR(6) DEFAULT NULL, passport_issuer VARCHAR(255) DEFAULT NULL, passport_issuance_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, passport_citizenship VARCHAR(255) DEFAULT NULL, passport_unit_code VARCHAR(255) DEFAULT NULL, passport_birth_day TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, passport_fact_country TEXT DEFAULT NULL, passport_fact_region TEXT DEFAULT NULL, passport_fact_city TEXT DEFAULT NULL, passport_fact_index TEXT DEFAULT NULL, passport_fact_street TEXT DEFAULT NULL, passport_fact_house TEXT DEFAULT NULL, passport_legal_country TEXT DEFAULT NULL, passport_legal_region TEXT DEFAULT NULL, passport_legal_city TEXT DEFAULT NULL, passport_legal_index TEXT DEFAULT NULL, passport_legal_street TEXT DEFAULT NULL, passport_legal_house TEXT DEFAULT NULL, passport_inn VARCHAR(255) DEFAULT NULL, passport_snils VARCHAR(20) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_91D54B1FCCFA12B8 ON profile_representatives (profile_id)');
        $this->addSql('COMMENT ON COLUMN profile_representatives.id IS \'(DC2Type:profile_representative_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_representatives.profile_id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_representatives.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN profile_representatives.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN profile_representatives.passport_issuance_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN profile_representatives.passport_birth_day IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE profile_requisites (id VARCHAR(255) NOT NULL, payment_id VARCHAR(255) DEFAULT NULL, payment_account VARCHAR(20) NOT NULL, bank_name VARCHAR(255) NOT NULL, bank_bik VARCHAR(9) NOT NULL, correspondent_account VARCHAR(20) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, bank_address VARCHAR(255) DEFAULT NULL, personal_account VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4BDAA30B4C3A3BB ON profile_requisites (payment_id)');
        $this->addSql('COMMENT ON COLUMN profile_requisites.id IS \'(DC2Type:profile_requisite_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_requisites.changed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN profile_requisites.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE profile_xml_document_history (id UUID NOT NULL, xml_document_id UUID DEFAULT NULL, moderator_id VARCHAR(255) DEFAULT NULL, action VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_ip VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9B2342CB573F85BD ON profile_xml_document_history (xml_document_id)');
        $this->addSql('CREATE INDEX IDX_9B2342CBD0AFA354 ON profile_xml_document_history (moderator_id)');
        $this->addSql('COMMENT ON COLUMN profile_xml_document_history.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE profile_xml_documents (id UUID NOT NULL, profile_id UUID DEFAULT NULL, moderator_id VARCHAR(255) DEFAULT NULL, id_number INT NOT NULL, status VARCHAR(255) NOT NULL, status_tactic VARCHAR(255) NOT NULL, file TEXT NOT NULL, hash VARCHAR(255) NOT NULL, sign TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, moderator_comment TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_21159E51CCFA12B8 ON profile_xml_documents (profile_id)');
        $this->addSql('CREATE INDEX IDX_21159E51D0AFA354 ON profile_xml_documents (moderator_id)');
        $this->addSql('COMMENT ON COLUMN profile_xml_documents.profile_id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN profile_xml_documents.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE protocols (id UUID NOT NULL, procedure_id UUID DEFAULT NULL, id_number VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, reason VARCHAR(255) NOT NULL, organizer_comment VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, xml_file TEXT NOT NULL, xml_hash_organizer VARCHAR(255) NOT NULL, xml_sign_organizer TEXT NOT NULL, xml_signed_at_organizer TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, xml_certificate_thumbprint_organizer TEXT NOT NULL, xml_hash_participant VARCHAR(255) DEFAULT NULL, xml_sign_participant TEXT DEFAULT NULL, xml_signed_at_participant TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, xml_certificate_thumbprint_participant TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_64AC020C1624BCD2 ON protocols (procedure_id)');
        $this->addSql('COMMENT ON COLUMN protocols.id IS \'(DC2Type:protocol_id)\'');
        $this->addSql('COMMENT ON COLUMN protocols.procedure_id IS \'(DC2Type:procedure_id)\'');
        $this->addSql('COMMENT ON COLUMN protocols.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN protocols.xml_signed_at_organizer IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN protocols.xml_signed_at_participant IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE old_records.protocols (id UUID NOT NULL, procedure_id UUID NOT NULL, name TEXT NOT NULL, text TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4D28655F1624BCD2 ON old_records.protocols (procedure_id)');
        $this->addSql('COMMENT ON COLUMN old_records.protocols.id IS \'(DC2Type:old_protocol_id)\'');
        $this->addSql('COMMENT ON COLUMN old_records.protocols.procedure_id IS \'(DC2Type:old_procedure_id)\'');
        $this->addSql('CREATE TABLE roles (id UUID NOT NULL, name VARCHAR(255) NOT NULL, role_constant VARCHAR(255) NOT NULL, permissions JSON NOT NULL, version INT DEFAULT 1 NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B63E2EC75E237E06 ON roles (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B63E2EC7E1B933E9 ON roles (role_constant)');
        $this->addSql('COMMENT ON COLUMN roles.id IS \'(DC2Type:role_id)\'');
        $this->addSql('COMMENT ON COLUMN roles.permissions IS \'(DC2Type:role_permissions)\'');
        $this->addSql('CREATE TABLE settings (id UUID NOT NULL, key VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E545A0C58A90ABA9 ON settings (key)');
        $this->addSql('CREATE TABLE subscribe_tariffs (id VARCHAR(255) NOT NULL, tariff_id VARCHAR(255) DEFAULT NULL, profile_id UUID DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_903BE0F792348FD2 ON subscribe_tariffs (tariff_id)');
        $this->addSql('CREATE INDEX IDX_903BE0F7CCFA12B8 ON subscribe_tariffs (profile_id)');
        $this->addSql('COMMENT ON COLUMN subscribe_tariffs.profile_id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN subscribe_tariffs.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscribe_tariffs.expires IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE tariff (id VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, cost VARCHAR(255) NOT NULL, period INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, unlimited BOOLEAN NOT NULL, status VARCHAR(255) NOT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, default_percent DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN tariff.cost IS \'(DC2Type:money)\'');
        $this->addSql('COMMENT ON COLUMN tariff.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN tariff.archived_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE tasks (id UUID NOT NULL, user_id VARCHAR(255) DEFAULT NULL, title TEXT NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_50586597A76ED395 ON tasks (user_id)');
        $this->addSql('COMMENT ON COLUMN tasks.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE transaction_documents (id UUID NOT NULL, transaction_id VARCHAR(255) DEFAULT NULL, hash VARCHAR(255) NOT NULL, sign TEXT NOT NULL, xml TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E197E9CB2FC0CB0F ON transaction_documents (transaction_id)');
        $this->addSql('CREATE TABLE user_users (id VARCHAR(255) NOT NULL, profile_id UUID DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, email VARCHAR(255) DEFAULT NULL, password_hash VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, new_email VARCHAR(255) DEFAULT NULL, client_ip VARCHAR(255) NOT NULL, confirm_token_token VARCHAR(255) DEFAULT NULL, confirm_token_expires TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reset_token_token VARCHAR(255) DEFAULT NULL, reset_token_expires TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, new_email_reset_token_token VARCHAR(255) DEFAULT NULL, new_email_reset_token_expires TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F6415EB1F464BC96 ON user_users (confirm_token_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F6415EB17ACC114B ON user_users (new_email_reset_token_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F6415EB1CCFA12B8 ON user_users (profile_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F6415EB1E7927C74 ON user_users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F6415EB186EC69F0 ON user_users (reset_token_token)');
        $this->addSql('COMMENT ON COLUMN user_users.profile_id IS \'(DC2Type:profile_profile_id)\'');
        $this->addSql('COMMENT ON COLUMN user_users.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_users.confirm_token_expires IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_users.reset_token_expires IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_users.new_email_reset_token_expires IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE auction_offers ADD CONSTRAINT FK_A3D5A81A4D9866B8 FOREIGN KEY (bid_id) REFERENCES bids (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auction_offers ADD CONSTRAINT FK_A3D5A81A57B8F0DE FOREIGN KEY (auction_id) REFERENCES auctions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auctions ADD CONSTRAINT FK_72D6E9005DFCD4B8 FOREIGN KEY (winner_id) REFERENCES profile_profiles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auctions ADD CONSTRAINT FK_72D6E900A8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lots (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bid_documents ADD CONSTRAINT FK_388B21574D9866B8 FOREIGN KEY (bid_id) REFERENCES bids (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bid_xml_documents ADD CONSTRAINT FK_33B397D54D9866B8 FOREIGN KEY (bid_id) REFERENCES bids (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bids ADD CONSTRAINT FK_3FF09E1E9D1C3019 FOREIGN KEY (participant_id) REFERENCES profile_profiles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bids ADD CONSTRAINT FK_3FF09E1EA8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lots (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bids ADD CONSTRAINT FK_3FF09E1E95EDF9EA FOREIGN KEY (requisite_id) REFERENCES profile_requisites (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bids ADD CONSTRAINT FK_3FF09E1E7599DDED FOREIGN KEY (subscribe_tariff_id) REFERENCES subscribe_tariffs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE certificates ADD CONSTRAINT FK_8D26FB5FA76ED395 FOREIGN KEY (user_id) REFERENCES user_users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commission_members ADD CONSTRAINT FK_EC75342F202D1EB2 FOREIGN KEY (commission_id) REFERENCES commissions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commissions ADD CONSTRAINT FK_7EA273CCCCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile_profiles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE old_records.documents ADD CONSTRAINT FK_8B3415DB1624BCD2 FOREIGN KEY (procedure_id) REFERENCES old_records.procedures (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE levels ADD CONSTRAINT FK_9F2A6419B2529590 FOREIGN KEY (id_tariff) REFERENCES tariff (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lot_documents ADD CONSTRAINT FK_83A64CCCA8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lots (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lots ADD CONSTRAINT FK_916087CE1624BCD2 FOREIGN KEY (procedure_id) REFERENCES procedures (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lots ADD CONSTRAINT FK_916087CE57B8F0DE FOREIGN KEY (auction_id) REFERENCES auctions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE old_records.notice ADD CONSTRAINT FK_94AF0DF81624BCD2 FOREIGN KEY (procedure_id) REFERENCES old_records.procedures (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES user_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_transactions ADD CONSTRAINT FK_8C58AD564D9866B8 FOREIGN KEY (bid_id) REFERENCES bids (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_transactions ADD CONSTRAINT FK_8C58AD564C3A3BB FOREIGN KEY (payment_id) REFERENCES profile_payments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_transactions ADD CONSTRAINT FK_8C58AD5695EDF9EA FOREIGN KEY (requisite_id) REFERENCES profile_requisites (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE procedure_documents ADD CONSTRAINT FK_6DD360031624BCD2 FOREIGN KEY (procedure_id) REFERENCES procedures (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE procedure_xml_document_history ADD CONSTRAINT FK_A851F434573F85BD FOREIGN KEY (xml_document_id) REFERENCES procedure_xml_documents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE procedure_xml_document_history ADD CONSTRAINT FK_A851F434D0AFA354 FOREIGN KEY (moderator_id) REFERENCES user_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE procedure_xml_documents ADD CONSTRAINT FK_6FE79AF01624BCD2 FOREIGN KEY (procedure_id) REFERENCES procedures (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE procedure_xml_documents ADD CONSTRAINT FK_6FE79AF0D0AFA354 FOREIGN KEY (moderator_id) REFERENCES user_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE procedures ADD CONSTRAINT FK_969AFE42CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile_profiles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE procedures ADD CONSTRAINT FK_969AFE4232C8A3DE FOREIGN KEY (organization_id) REFERENCES profile_organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE procedures ADD CONSTRAINT FK_969AFE42FC3FF006 FOREIGN KEY (representative_id) REFERENCES profile_representatives (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_documents ADD CONSTRAINT FK_1E2F9BF3CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile_profiles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_organizations ADD CONSTRAINT FK_6C7FB9BFCCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile_profiles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_payments ADD CONSTRAINT FK_9CB8FA83CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile_profiles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_profiles ADD CONSTRAINT FK_725AE481D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_profiles ADD CONSTRAINT FK_725AE481A76ED395 FOREIGN KEY (user_id) REFERENCES user_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_profiles ADD CONSTRAINT FK_725AE48132C8A3DE FOREIGN KEY (organization_id) REFERENCES profile_organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_profiles ADD CONSTRAINT FK_725AE481FC3FF006 FOREIGN KEY (representative_id) REFERENCES profile_representatives (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_profiles ADD CONSTRAINT FK_725AE48199223FFD FOREIGN KEY (certificate_id) REFERENCES certificates (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_profiles ADD CONSTRAINT FK_725AE4817599DDED FOREIGN KEY (subscribe_tariff_id) REFERENCES subscribe_tariffs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_profiles ADD CONSTRAINT FK_725AE4814C3A3BB FOREIGN KEY (payment_id) REFERENCES profile_payments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_representatives ADD CONSTRAINT FK_91D54B1FCCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile_profiles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_requisites ADD CONSTRAINT FK_4BDAA30B4C3A3BB FOREIGN KEY (payment_id) REFERENCES profile_payments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_xml_document_history ADD CONSTRAINT FK_9B2342CB573F85BD FOREIGN KEY (xml_document_id) REFERENCES profile_xml_documents (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_xml_document_history ADD CONSTRAINT FK_9B2342CBD0AFA354 FOREIGN KEY (moderator_id) REFERENCES user_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_xml_documents ADD CONSTRAINT FK_21159E51CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile_profiles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profile_xml_documents ADD CONSTRAINT FK_21159E51D0AFA354 FOREIGN KEY (moderator_id) REFERENCES user_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE protocols ADD CONSTRAINT FK_64AC020C1624BCD2 FOREIGN KEY (procedure_id) REFERENCES procedures (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE old_records.protocols ADD CONSTRAINT FK_4D28655F1624BCD2 FOREIGN KEY (procedure_id) REFERENCES old_records.procedures (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscribe_tariffs ADD CONSTRAINT FK_903BE0F792348FD2 FOREIGN KEY (tariff_id) REFERENCES tariff (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscribe_tariffs ADD CONSTRAINT FK_903BE0F7CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile_profiles (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT FK_50586597A76ED395 FOREIGN KEY (user_id) REFERENCES user_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transaction_documents ADD CONSTRAINT FK_E197E9CB2FC0CB0F FOREIGN KEY (transaction_id) REFERENCES payment_transactions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_users ADD CONSTRAINT FK_F6415EB1CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile_profiles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE auction_offers DROP CONSTRAINT FK_A3D5A81A57B8F0DE');
        $this->addSql('ALTER TABLE lots DROP CONSTRAINT FK_916087CE57B8F0DE');
        $this->addSql('ALTER TABLE auction_offers DROP CONSTRAINT FK_A3D5A81A4D9866B8');
        $this->addSql('ALTER TABLE bid_documents DROP CONSTRAINT FK_388B21574D9866B8');
        $this->addSql('ALTER TABLE bid_xml_documents DROP CONSTRAINT FK_33B397D54D9866B8');
        $this->addSql('ALTER TABLE payment_transactions DROP CONSTRAINT FK_8C58AD564D9866B8');
        $this->addSql('ALTER TABLE profile_profiles DROP CONSTRAINT FK_725AE48199223FFD');
        $this->addSql('ALTER TABLE commission_members DROP CONSTRAINT FK_EC75342F202D1EB2');
        $this->addSql('ALTER TABLE auctions DROP CONSTRAINT FK_72D6E900A8CBA5F7');
        $this->addSql('ALTER TABLE bids DROP CONSTRAINT FK_3FF09E1EA8CBA5F7');
        $this->addSql('ALTER TABLE lot_documents DROP CONSTRAINT FK_83A64CCCA8CBA5F7');
        $this->addSql('ALTER TABLE transaction_documents DROP CONSTRAINT FK_E197E9CB2FC0CB0F');
        $this->addSql('ALTER TABLE procedure_xml_document_history DROP CONSTRAINT FK_A851F434573F85BD');
        $this->addSql('ALTER TABLE lots DROP CONSTRAINT FK_916087CE1624BCD2');
        $this->addSql('ALTER TABLE procedure_documents DROP CONSTRAINT FK_6DD360031624BCD2');
        $this->addSql('ALTER TABLE procedure_xml_documents DROP CONSTRAINT FK_6FE79AF01624BCD2');
        $this->addSql('ALTER TABLE protocols DROP CONSTRAINT FK_64AC020C1624BCD2');
        $this->addSql('ALTER TABLE old_records.documents DROP CONSTRAINT FK_8B3415DB1624BCD2');
        $this->addSql('ALTER TABLE old_records.notice DROP CONSTRAINT FK_94AF0DF81624BCD2');
        $this->addSql('ALTER TABLE old_records.protocols DROP CONSTRAINT FK_4D28655F1624BCD2');
        $this->addSql('ALTER TABLE procedures DROP CONSTRAINT FK_969AFE4232C8A3DE');
        $this->addSql('ALTER TABLE profile_profiles DROP CONSTRAINT FK_725AE48132C8A3DE');
        $this->addSql('ALTER TABLE payment_transactions DROP CONSTRAINT FK_8C58AD564C3A3BB');
        $this->addSql('ALTER TABLE profile_profiles DROP CONSTRAINT FK_725AE4814C3A3BB');
        $this->addSql('ALTER TABLE profile_requisites DROP CONSTRAINT FK_4BDAA30B4C3A3BB');
        $this->addSql('ALTER TABLE auctions DROP CONSTRAINT FK_72D6E9005DFCD4B8');
        $this->addSql('ALTER TABLE bids DROP CONSTRAINT FK_3FF09E1E9D1C3019');
        $this->addSql('ALTER TABLE commissions DROP CONSTRAINT FK_7EA273CCCCFA12B8');
        $this->addSql('ALTER TABLE procedures DROP CONSTRAINT FK_969AFE42CCFA12B8');
        $this->addSql('ALTER TABLE profile_documents DROP CONSTRAINT FK_1E2F9BF3CCFA12B8');
        $this->addSql('ALTER TABLE profile_organizations DROP CONSTRAINT FK_6C7FB9BFCCFA12B8');
        $this->addSql('ALTER TABLE profile_payments DROP CONSTRAINT FK_9CB8FA83CCFA12B8');
        $this->addSql('ALTER TABLE profile_representatives DROP CONSTRAINT FK_91D54B1FCCFA12B8');
        $this->addSql('ALTER TABLE profile_xml_documents DROP CONSTRAINT FK_21159E51CCFA12B8');
        $this->addSql('ALTER TABLE subscribe_tariffs DROP CONSTRAINT FK_903BE0F7CCFA12B8');
        $this->addSql('ALTER TABLE user_users DROP CONSTRAINT FK_F6415EB1CCFA12B8');
        $this->addSql('ALTER TABLE procedures DROP CONSTRAINT FK_969AFE42FC3FF006');
        $this->addSql('ALTER TABLE profile_profiles DROP CONSTRAINT FK_725AE481FC3FF006');
        $this->addSql('ALTER TABLE bids DROP CONSTRAINT FK_3FF09E1E95EDF9EA');
        $this->addSql('ALTER TABLE payment_transactions DROP CONSTRAINT FK_8C58AD5695EDF9EA');
        $this->addSql('ALTER TABLE profile_xml_document_history DROP CONSTRAINT FK_9B2342CB573F85BD');
        $this->addSql('ALTER TABLE profile_profiles DROP CONSTRAINT FK_725AE481D60322AC');
        $this->addSql('ALTER TABLE bids DROP CONSTRAINT FK_3FF09E1E7599DDED');
        $this->addSql('ALTER TABLE profile_profiles DROP CONSTRAINT FK_725AE4817599DDED');
        $this->addSql('ALTER TABLE levels DROP CONSTRAINT FK_9F2A6419B2529590');
        $this->addSql('ALTER TABLE subscribe_tariffs DROP CONSTRAINT FK_903BE0F792348FD2');
        $this->addSql('ALTER TABLE certificates DROP CONSTRAINT FK_8D26FB5FA76ED395');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE procedure_xml_document_history DROP CONSTRAINT FK_A851F434D0AFA354');
        $this->addSql('ALTER TABLE procedure_xml_documents DROP CONSTRAINT FK_6FE79AF0D0AFA354');
        $this->addSql('ALTER TABLE profile_profiles DROP CONSTRAINT FK_725AE481A76ED395');
        $this->addSql('ALTER TABLE profile_xml_document_history DROP CONSTRAINT FK_9B2342CBD0AFA354');
        $this->addSql('ALTER TABLE profile_xml_documents DROP CONSTRAINT FK_21159E51D0AFA354');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT FK_50586597A76ED395');
        $this->addSql('DROP TABLE auction_offers');
        $this->addSql('DROP TABLE auctions');
        $this->addSql('DROP TABLE bid_documents');
        $this->addSql('DROP TABLE bid_xml_documents');
        $this->addSql('DROP TABLE bids');
        $this->addSql('DROP TABLE certificates');
        $this->addSql('DROP TABLE commission_members');
        $this->addSql('DROP TABLE commissions');
        $this->addSql('DROP TABLE old_records.documents');
        $this->addSql('DROP TABLE holidays');
        $this->addSql('DROP TABLE levels');
        $this->addSql('DROP TABLE lot_documents');
        $this->addSql('DROP TABLE lots');
        $this->addSql('DROP TABLE news');
        $this->addSql('DROP TABLE old_records.notice');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE payment_transactions');
        $this->addSql('DROP TABLE procedure_documents');
        $this->addSql('DROP TABLE procedure_xml_document_history');
        $this->addSql('DROP TABLE procedure_xml_documents');
        $this->addSql('DROP TABLE procedures');
        $this->addSql('DROP TABLE old_records.procedures');
        $this->addSql('DROP TABLE profile_documents');
        $this->addSql('DROP TABLE profile_organizations');
        $this->addSql('DROP TABLE profile_payments');
        $this->addSql('DROP TABLE profile_profiles');
        $this->addSql('DROP TABLE profile_representatives');
        $this->addSql('DROP TABLE profile_requisites');
        $this->addSql('DROP TABLE profile_xml_document_history');
        $this->addSql('DROP TABLE profile_xml_documents');
        $this->addSql('DROP TABLE protocols');
        $this->addSql('DROP TABLE old_records.protocols');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE settings');
        $this->addSql('DROP TABLE subscribe_tariffs');
        $this->addSql('DROP TABLE tariff');
        $this->addSql('DROP TABLE tasks');
        $this->addSql('DROP TABLE transaction_documents');
        $this->addSql('DROP TABLE user_users');
    }
}
